### ISSUE TITLE
文件太大

### ISSUE THREAD

**Issue by MrASDB** [greenaway07/GirlDress#14]
建议提交之前自行压一下图，毕竟一个学习性项目尽是高清大图也没有什么实际意义，而且不是作为图床使用的话，原图实在太过占用资源了，时间久了拉取项目也得下载很久

**Comment by greenaway07** [comment]
是这样的呢。我在README里提示一下。谢谢提醒...

**Comment by greenaway07** [comment]
> 是这样的呢。我在README里提示一下。谢谢提醒...

然后现有的有待resize
