### ISSUE TITLE
建议换个名字（至少去掉尾部的“-”）因为太不利于传播了

### ISSUE THREAD

**Issue by shuiRong** [greenaway07/GirlDress#16]
如图，QQ没有识别出来最后的“-”，这样其他人在点击链接的时候就会“404 Not Found”，十分不利于传播

![image](https://user-images.githubusercontent.com/16076993/52040534-b3875100-2572-11e9-8c27-ce9e98125dbb.png)

**Comment by greenaway07** [comment]
改了,去掉两个连字符了
