### ISSUE TITLE
403_Forbidden  这位在两个项目里都有啊   突然性别成谜了

### ISSUE THREAD

**Issue by Takicheng** [greenaway07/GirlDress#51]
安能辨你是雄雌

**Comment by greenaway07** [comment]
应该是男的，我翻看博客了。谢谢提醒♪(･ω･)ﾉ

**Comment by jshensh** [comment]
@greenaway07 mtf 也是女性阿

**Comment by jshensh** [comment]
@greenaway07 不好意思是女的

**Comment by jshensh** [comment]
@greenaway07 况且另外一边的 repo 是不限性别的

**Comment by lilydjwg** [comment]
You should be this, you should be that. You should be whatever people think you are, instead of what you really are, or what the truth is.
